name: Build Schnerror

on:
  push:
    branches:
      - master
    
jobs:
  build:
    # laut (altem) tutorial ubuntu-20.04 , aktuell ist 22.04
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install dependencies & build
        run:  |
          npm ci
          npm run build

      - name: Deploy
        # error exit code 128 -> settings,action,general,workflow permissions:read&write,allow github actions to approve pull requests  
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          github_token: ${{ secrets.GITHUB_TOKEN }}